---
AWSTemplateFormatVersion: '2010-09-09'
Description: Housekeeping-unrestricted-sg-lambdas.

Parameters:

  ArtifactBucketName:
    Type: String
    Description: Base URL for artifacts in S3. From deployspec compiler.

  ArtifactKeyPrefix:
    Type: String
    Description: Build path prefix for this app. From deployspec compiler.

  AutomationBranchS3Prefix:
    Type: String
    Description: Location to download/upload state files. Assumes ArtifactBucketName bucket.

  LambdaFunctionNamePrefix:
    Type: String

  ListSgRole:
    Type: String
    Default: "arn:aws:iam::1232:role/PipelineControl"


Resources:

  getvolumedetailsLambda:
    Type: AWS::Lambda::Function
    # DependsOn:
    #   - CleanLogGroupsLogGroup
    Properties:
      Description: List volumes details in the all account.
      Code:
        S3Bucket:
          Ref: ArtifactBucketName
        S3Key:
          Fn::Sub: "${ArtifactKeyPrefix}/getting_volumes_details.zip"
      FunctionName:
        Fn::Sub: "${LambdaFunctionNamePrefix}-getting_volumes_details"
      Handler: getting_volumes_details.lambda_handler
      MemorySize: 256
      Role: !Ref ListSgRole
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          AUTOMATION_BUCKET: !Ref ArtifactBucketName
          AUTOMATION_BRANCH_S3_PREFIX: !Ref AutomationBranchS3Prefix # Upload/download to s3.
          ACCOUNT_ID: !Sub "${AWS::AccountId}" # used for filename, useful when testing locally on multiple accounts.
          

  LogsEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule get volume details lambda invoke."
      ScheduleExpression: "cron(0 20 ? * 1 *)" # 8pm UTC weekly (4am SGT)
      Targets:
        - Id: getvolumedetailsLambdaTarget
          Arn: !GetAtt getvolumedetailsLambda.Arn

  LogGroupsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: getvolumedetailsLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LogsEventRule.Arn

Outputs:

  getvolumedetailsLambdaArn:
    Value: !GetAtt getvolumedetailsLambda.Arn
